const allWorkouts = [
  {
    id: 1,
    title: "Jumping Jacks",
    image: "jumping-jacks",
    type: "duration",
  },
  {
    id: 2,
    title: "Abdominal Crunches",
    image: "abdominal-crunches",
    type: "repetition",
  },
  {
    id: 3,
    title: "Russian Twist",
    image: "russian-twist",
    type: "repetition",
  },
  {
    id: 4,
    title: "Heel Touch",
    image: "heel-touch",
    type: "repetition",
  },
  {
    id: 5,
    title: "Mountain Climber",
    image: "mountain-climber",
    type: "repetition",
  },
  {
    id: 6,
    title: "Leg Raises",
    image: "leg-raises",
    type: "repetition",
  },
  {
    id: 7,
    title: "Plank",
    image: "plank",
    type: "duration",
  },
  {
    id: 8,
    title: "Heel Touch",
    image: "heel-touch",
    type: "repetition",
  },
  {
    id: 9,
    title: "Cobra Stretch",
    image: "cobra-stretch",
    type: "duration",
  },
  {
    id: 10,
    title: "Spine Lumbar Twist Stretch Left",
    image: "spine-lumbar-twist-stretch-left",
    type: "duration",
  },
  {
    id: 11,
    title: "Spine Lumbar Twist Stretch Right",
    image: "spine-lumbar-twist-stretch-right",
    type: "duration",
  },
  {
    id: 12,
    title: "Crossover Crunch",
    image: "crossover-crunch",
    type: "repetition",
  },
  {
    id: 13,
    title: "Side Bridges Left",
    image: "side-bridges-left",
    type: "repetition",
  },
  {
    id: 14,
    title: "Side Bridges Right",
    image: "side-bridges-right",
    type: "repetition",
  },
  {
    id: 15,
    title: "Butt Bridge",
    image: "butt-bridge",
    type: "repetition",
  },
  {
    id: 16,
    title: "Bicycle Crunches",
    image: "bicycle-crunches",
    type: "repetition",
  },
  {
    id: 17,
    title: "V-Up",
    image: "v-up",
    type: "repetition",
  },
  {
    id: 18,
    title: "Push-Up & Rotation",
    image: "push-up-and-rotation",
    type: "repetition",
  },
  {
    id: 19,
    title: "Side Plank Right",
    image: "side-plank-right",
    type: "duration",
  },
  {
    id: 20,
    title: "Side Plank Left",
    image: "side-plank-left",
    type: "duration",
  },
  {
    id: 21,
    title: "Cobra Stretch",
    image: "cobra-stretch",
    type: "duration",
  },
  {
    id: 22,
    title: "Sit-Ups",
    image: "sit-ups",
    type: "repetition",
  },
  {
    id: 23,
    title: "Side Bridges Left",
    image: "side-bridges-left",
    type: "repetition",
  },
  {
    id: 24,
    title: "Side Bridges Right",
    image: "side-bridges-right",
    type: "repetition",
  },
  {
    id: 25,
    title: "Incline Push-Ups",
    image: "incline-push-ups",
    type: "repetition",
  },
  {
    id: 26,
    title: "Push-Ups",
    image: "push-ups",
    type: "repetition",
  },
  {
    id: 27,
    title: "Wide Arm Push-Ups",
    image: "wide-arm-push-ups",
    type: "repetition",
  },
  {
    id: 28,
    title: "Triceps Dips",
    image: "triceps-dips",
    type: "repetition",
  },
  {
    id: 29,
    title: "Knee Push-ups",
    image: "knee-push-ups",
    type: "repetition",
  },
  {
    id: 30,
    title: "Chest Stretch",
    image: "chest-stretch",
    type: "duration",
  },
  {
    id: 31,
    title: "Hindu Push-ups",
    image: "hindu-push-ups",
    type: "repetition",
  },
  {
    id: 32,
    title: "Staggered Push-Ups",
    image: "staggered-push-ups",
    type: "repetition",
  },
  {
    id: 33,
    title: "Decline Push-ups",
    image: "decline-push-ups",
    type: "repetition",
  },
  {
    id: 34,
    title: "Shoulder Stretch",
    image: "shoulder-stretch",
    type: "duration",
  },
  {
    id: 35,
    title: "Arm Circles",
    image: "arm-circles",
    type: "repetition",
  },
  {
    id: 36,
    title: "Burpees",
    image: "burpees",
    type: "repetition",
  },
  {
    id: 37,
    title: "Diamond Push-Ups",
    image: "diamond-push-ups",
    type: "repetition",
  },
  {
    id: 38,
    title: "Box Push-Ups",
    image: "box-push-ups",
    type: "repetition",
  },
  {
    id: 39,
    title: "Spiderman Push-Ups",
    image: "spiderman-push-ups",
    type: "repetition",
  },
  {
    id: 40,
    title: "Side Arm Raise",
    image: "side-arm-raise",
    type: "duration",
  },
  {
    id: 41,
    title: "Arm Circles Clockwise",
    image: "arm-circles-clockwise",
    type: "duration",
  },
  {
    id: 42,
    title: "Arm Circles Counter-Clockwise",
    image: "arm-circles-counter-clockwise",
    type: "duration",
  },
  {
    id: 43,
    title: "Chest Press Pulse",
    image: "chest-press-pulse",
    type: "duration",
  },
  {
    id: 44,
    title: "Leg Barbell Curl Left",
    image: "leg-barbell-curl-left",
    type: "repetition",
  },
  {
    id: 45,
    title: "Leg Barbell Curl Right",
    image: "leg-barbell-curl-right",
    type: "repetition",
  },
  {
    id: 46,
    title: "Diagonal Plank",
    image: "diagonal-plank",
    type: "repetition",
  },
  {
    id: 47,
    title: "Punches",
    image: "punches",
    type: "duration",
  },
  {
    id: 48,
    title: "Inchworms",
    image: "inchworms",
    type: "repetition",
  },
  {
    id: 49,
    title: "Wall Push-Ups",
    image: "wall-push-ups",
    type: "duration",
  },
  {
    id: 50,
    title: "Triceps Stretch Left",
    image: "triceps-stretch-left",
    type: "duration",
  },
  {
    id: 51,
    title: "Triceps Stretch Right",
    image: "triceps-stretch-right",
    type: "duration",
  },
  {
    id: 52,
    title: "Standing Biceps Stretch Left",
    image: "standing-biceps-stretch-left",
    type: "duration",
  },
  {
    id: 53,
    title: "Standing Biceps Stretch Right",
    image: "standing-biceps-stretch-right",
    type: "duration",
  },
  {
    id: 54,
    title: "Military Push-Ups",
    image: "military-push-up",
    type: "repetition",
  },
  {
    id: 55,
    title: "Alternating Hooks",
    image: "alternating-hooks",
    type: "repetition",
  },
  {
    id: 56,
    title: "Skipping Without Rope",
    image: "skipping-without-rope",
    type: "duration",
  },
  {
    id: 57,
    title: "Arm Scissors",
    image: "arm-circles",
    type: "duration",
  },
  {
    id: 58,
    title: "Arm Curls Crunch Left",
    image: "arm-curls-crunch-left",
    type: "repetition",
  },
  {
    id: 59,
    title: "Arm Curls Crunch Right",
    image: "arm-curls-crunch-right",
    type: "repetition",
  },
  {
    id: 60,
    title: "Floor Triceps Dips",
    image: "floor-triceps-dips",
    type: "repetition",
  },
  {
    id: 61,
    title: "Shoulder Gators",
    image: "shoulder-gators",
    type: "repetition",
  },
  {
    id: 62,
    title: "Doorway Curls Left",
    image: "doorway-curls-left",
    type: "repetition",
  },
  {
    id: 63,
    title: "Doorway Curls Right",
    image: "doorway-curls-right",
    type: "repetition",
  },
  {
    id: 64,
    title: "Modified Push-Up Low Hold",
    image: "modified-push-up-low-hold",
    type: "duration",
  },
  {
    id: 65,
    title: "Side Hop",
    image: "side-hop",
    type: "duration",
  },
  {
    id: 1,
    title: "Squats",
    image: "squats",
    type: "repetition",
  },
  {
    id: 66,
    title: "Side-Lying Leg Lift Left",
    image: "side-lying-leg-lift-left",
    type: "repetition",
  },
  {
    id: 67,
    title: "Side-Lying Leg Lift Right",
    image: "side-lying-leg-lift-right",
    type: "repetition",
  },
  {
    id: 68,
    title: "Backward Lunge",
    image: "backward-lunge",
    type: "repetition",
  },
  {
    id: 69,
    title: "Donkey Kicks Left",
    image: "donkey-kicks-left",
    type: "repetition",
  },
  {
    id: 70,
    title: "Donkey Kicks Right",
    image: "donkey-kicks-right",
    type: "repetition",
  },
  {
    id: 71,
    title: "Left Quad Stretch With Wall",
    image: "left-quad-stretch-with-wall",
    type: "duration",
  },
  {
    id: 72,
    title: "Right Quad Stretch With Wall",
    image: "right-quad-stretch-with-wall",
    type: "duration",
  },
  {
    id: 73,
    title: "Knee To Chest Stretch Right",
    image: "knee-to-chest-stretch-right",
    type: "duration",
  },
  {
    id: 74,
    title: "Knee To Chest Stretch Left",
    image: "knee-to-chest-stretch-left",
    type: "duration",
  },
  {
    id: 75,
    title: "Wall Calf Raises",
    image: "wall-calf-raises",
    type: "repetition",
  },
  {
    id: 76,
    title: "Sumo Squat Calf Raises With Wall",
    image: "sumo-squat-calf-raises-with-wall",
    type: "repetition",
  },
  {
    id: 77,
    title: "Calf Stretch Left",
    image: "calf-stretch-left",
    type: "duration",
  },
  {
    id: 78,
    title: "Calf Stretch Right",
    image: "calf-stretch-right",
    type: "duration",
  },
  {
    id: 79,
    title: "Fire Hydrant Left",
    image: "fire-hydrant-left",
    type: "repetition",
  },
  {
    id: 80,
    title: "Fire Hydrant Right",
    image: "fire-hydrant-right",
    type: "repetition",
  },
  {
    id: 81,
    title: "Lunges",
    image: "lunges",
    type: "repetition",
  },
  {
    id: 82,
    title: "Side Leg Circles Left",
    image: "side-leg-circles-left",
    type: "repetition",
  },
  {
    id: 83,
    title: "Side Leg Circles Right",
    image: "side-leg-circles-right",
    type: "repetition",
  },
  {
    id: 84,
    title: "Sumo Squat",
    image: "sumo-squat",
    type: "repetition",
  },
  {
    id: 85,
    title: "Reverse Flutter Kicks",
    image: "reverse-flutter-kicks",
    type: "repetition",
  },
  {
    id: 86,
    title: "Wall Sit",
    image: "wall-sit",
    type: "duration",
  },
  {
    id: 87,
    title: "Left Quad Stretch With Wall",
    image: "left-quad-stretch-with-wall",
    type: "duration",
  },
  {
    id: 88,
    title: "Right Quad Stretch With Wall",
    image: "right-quad-stretch-with-wall",
    type: "duration",
  },
  {
    id: 89,
    title: "Calf Raise With Splayed Foot",
    image: "calf-raises-with-splayed-foot",
    type: "repetition",
  },
  {
    id: 90,
    title: "Single Leg Calf Hop Left",
    image: "single-leg-calf-hop-left",
    type: "repetition",
  },
  {
    id: 91,
    title: "Single Leg Calf Hop Right",
    image: "single-leg-calf-hop-right",
    type: "repetition",
  },
  {
    id: 92,
    title: "Bottom Leg Lift Left",
    image: "bottom-lef-lift-left",
    type: "repetition",
  },
  {
    id: 93,
    title: "Bottom Leg Lift Right",
    image: "bottom-lef-lift-right",
    type: "repetition",
  },
  {
    id: 94,
    title: "Curtsy Lunges",
    image: "curtsy-lunges",
    type: "repetition",
  },
  {
    id: 95,
    title: "Jumping Squats",
    image: "jumping-jacks",
    type: "repetition",
  },
  {
    id: 96,
    title: "Glute Kick Back Left",
    image: "glute-kick-back-left",
    type: "repetition",
  },
  {
    id: 97,
    title: "Glute Kick Back Right",
    image: "glute-kick-back-right",
    type: "repetition",
  },
  {
    id: 98,
    title: "Lying Butterfly Stretch",
    image: "lying-butterfly-stretch",
    type: "duration",
  },
  {
    id: 99,
    title: "Leaning Stretches Raises",
    image: "leaning-stretcher-raises",
    type: "repetition",
  },
  {
    id: 100,
    title: "Wall Resisting Single Leg Calf Raise Left",
    image: "wall-resisting-single-leg-calf-raise-left",
    type: "repetition",
  },
  {
    id: 101,
    title: "Wall Resisting Single Leg Calf Raise Right",
    image: "wall-resisting-single-leg-calf-raise-right",
    type: "repetition",
  },
  {
    id: 102,
    title: "Triceps Kickbacks",
    image: "triceps-kickbacks",
    type: "repetition",
  },
  {
    id: 103,
    title: "Rhomboid Pulls",
    image: "rhomboid-pulls",
    type: "repetition",
  },
  {
    id: 104,
    title: "Cat Cow Pose",
    image: "cat-cow-pose",
    type: "duration",
  },
  {
    id: 105,
    title: "Hip Hinge",
    image: "hip-hinge",
    type: "repetition",
  },
  {
    id: 106,
    title: "Side-Lying Floor Stretch Left",
    image: "side-lying-floor-stretch-left",
    type: "duration",
  },
  {
    id: 107,
    title: "Side-Lying Floor Stretch Right",
    image: "side-lying-floor-stretch-right",
    type: "duration",
  },
  {
    id: 108,
    title: "Hover Push Up",
    image: "hover-push-up",
    type: "repetition",
  },
  {
    id: 109,
    title: "Swimmer & Superman",
    image: "swimmer-and-superman",
    type: "repetition",
  },
  {
    id: 110,
    title: "Child's Pose",
    image: "childs-pose",
    type: "duration",
  },
  {
    id: 111,
    title: "Prone Triceps Push Ups",
    image: "prone-triceps-push-ups",
    type: "repetition",
  },
  {
    id: 112,
    title: "Reclined Rhomboid Squeezes",
    image: "reclined-rhomboid-squeezes",
    type: "repetition",
  },
  {
    id: 113,
    title: "Hyperextension",
    image: "hyperextension",
    type: "repetition",
  },
  {
    id: 114,
    title: "Pike Push Ups",
    image: "pike-push-ups",
    type: "repetition",
  },
  {
    id: 115,
    title: "Reverse Push-Ups",
    image: "reverse-push-ups",
    type: "repetition",
  },
  {
    id: 116,
    title: "Supine Push Up",
    image: "supine-push-up",
    type: "repetition",
  },
  {
    id: 117,
    title: "Floor Y Raises",
    image: "floor-y-raises",
    type: "repetition",
  },
  {
    id: 118,
    title: "Reverse Snow Angels",
    image: "reverse-slow-angels",
    type: "repetition",
  },
]
const workouts = {
  abs: {
    beginner: [
      ["jumping-jacks", 20],
      ["abdominal-crunches", 16],
      ["russian-twist", 20],
      ["heel-touch", 20],
      ["mountain-climber", 16],
      ["leg-raises", 16],
      ["plank", 20],
      ["abdominal-crunches", 12],
      ["russian-twist", 32],
      ["mountain-climber", 12],
      ["heel-touch", 20],
      ["leg-raises", 14],
      ["plank", 30],
      ["cobra-stretch", 30],
      ["spine-lumbar-twist-stretch-left", 30],
      ["spine-lumbar-twist-stretch-right", 30],
    ],
    intermediate: [
      ["jumping-jacks", 30],
      ["heel-touch", 26],
      ["crossover-crunch", 20],
      ["mountain-climber", 20],
      ["side-bridges-left", 12],
      ["side-bridges-right", 12],
      ["butt-bridge", 20],
      ["bicycle-crunches", 20],
      ["v-up", 20],
      ["heel-touch", 26],
      ["abdominal-crunches", 20],
      ["plank", 30],
      ["crossover-crunch", 20],
      ["leg-raises", 16],
      ["bicycle-crunches", 20],
      ["push-up-and-rotation", 20],
      ["side-plank-right", 20],
      ["side-plank-left", 20],
      ["cobra-stretch", 30],
      ["spine-lumbar-twist-stretch-left", 30],
      ["spine-lumbar-twist-stretch-right", 30],
    ],
    advanced: [
      ["jumping-jacks", 30],
      ["sit-ups", 20],
      ["side-bridges-left", 20],
      ["side-bridges-right", 20],
      ["abdominal-crunches", 30],
      ["bicycle-crunches", 24],
      ["side-plank-right", 20],
      ["side-plank-left", 20],
      ["v-up", 18],
      ["push-up-and-rotation", 24],
      ["russian-twist", 48],
      ["abdominal-crunches", 28],
      ["butt-bridge", 30],
      ["heel-touch", 34],
      ["mountain-climber", 30],
      ["crossover-crunch", 24],
      ["v-up", 16],
      ["plank", 60],
      ["cobra-stretch", 30],
      ["spine-lumbar-twist-stretch-left", 30],
      ["spine-lumbar-twist-stretch-right", 30],
    ],
  },
  chest: {
    beginner: [
      ["jumping-jacks", 30],
      ["incline-push-ups", 10],
      ["push-ups", 8],
      ["wide-arm-push-ups", 8],
      ["triceps-dips", 10],
      ["wide-arm-push-ups", 6],
      ["incline-push-ups", 8],
      ["triceps-dips", 8],
      ["knee-push-ups", 8],
      ["cobra-stretch", 20],
      ["chest-stretch", 20],
    ],
    intermediate: [
      ["jumping-jacks", 30],
      ["knee-push-ups", 12],
      ["push-ups", 12],
      ["wide-arm-push-ups", 16],
      ["hindu-push-ups", 10],
      ["staggered-push-ups", 12],
      ["triceps-dips", 10],
      ["knee-push-ups", 10],
      ["hindu-push-ups", 10],
      ["decline-push-ups", 12],
      ["staggered-push-ups", 10],
      ["shoulder-stretch", 30],
      ["cobra-stretch", 30],
      ["chest-stretch", 30],
    ],
    advanced: [
      ["jumping-jacks", 30],
      ["arm-circles", 20],
      ["shoulder-stretch", 30],
      ["burpees", 10],
      ["staggered-push-ups", 16],
      ["hindu-push-ups", 16],
      ["push-up-and-rotation", 12],
      ["diamond-push-ups", 16],
      ["box-push-ups", 12],
      ["hindu-push-ups", 12],
      ["spiderman-push-ups", 20],
      ["decline-push-ups", 12],
      ["burpees", 10],
      ["shoulder-stretch", 30],
      ["cobra-stretch", 30],
      ["chest-stretch", 30],
    ],
  },
  arm: {
    beginner: [
      ["arm-raises", 30],
      ["side-arm-raise", 30],
      ["triceps-dips", 10],
      ["arm-circles-clockwise", 30],
      ["arm-circles-counter-clockwise", 30],
      ["diamond-push-ups", 6],
      ["jumping-jacks", 30],
      ["chest-press-pulse", 16],
      ["leg-barbell-curl-left", 8],
      ["leg-barbell-curl-right", 8],
      ["diagonal-plank", 10],
      ["punches", 30],
      ["push-ups", 10],
      ["inchworms", 8],
      ["wall-calf-raises", 12],
      ["triceps-stretch-left", 30],
      ["triceps-stretch-right", 30],
      ["standing-biceps-stretch-left", 30],
      ["standing-biceps-stretch-right", 30],
    ],
    intermediate: [
      ["arm-circles-clockwise", 30],
      ["arm-circles-counter-clockwise", 30],
      ["floor-triceps-dips", 14],
      ["military-push-up", 12],
      ["alternating-hooks", 30],
      ["push-up-and-rotation", 12],
      ["leg-barbell-curl-left", 12],
      ["leg-barbell-curl-right", 12],
      ["floor-triceps-dips", 12],
      ["military-push-up", 10],
      ["alternating-hooks", 30],
      ["push-up-and-rotation", 10],
      ["leg-barbell-curl-left", 10],
      ["leg-barbell-curl-right", 10],
      ["skipping-without-rope", 30],
      ["push-ups", 14],
      ["burpees", 10],
      ["arm-scissors", 30],
      ["skipping-without-rope", 30],
      ["push-ups", 12],
      ["burpees", 8],
      ["triceps-stretch-left", 30],
      ["triceps-stretch-right", 30],
      ["standing-biceps-stretch-left", 30],
      ["standing-biceps-stretch-right", 30],
    ],
    advanced: [
      ["arm-circles-clockwise", 30],
      ["arm-circles-counter-clockwise", 30],
      ["skipping-without-rope", 30],
      ["leg-barbell-curl-left", 16],
      ["leg-barbell-curl-right", 16],
      ["burpees", 16],
      ["arm-curls-crunch-left", 14],
      ["arm-curls-crunch-right", 14],
      ["floor-triceps-dips", 18],
      ["alternating-hooks", 30],
      ["military-push-up", 14],
      ["shoulder-gators", 16],
      ["floor-triceps-dips", 16],
      ["alternating-hooks", 30],
      ["burpees", 16],
      ["arm-curls-crunch-left", 12],
      ["arm-curls-crunch-right", 12],
      ["military-push-up", 12],
      ["shoulder-gators", 16],
      ["doorway-curls-left", 8],
      ["doorway-curls-right", 8],
      ["modified-push-up-low-hold", 30],
      ["chest-press-pulse", 18],
      ["push-up-and-rotation", 12],
      ["triceps-stretch-left", 30],
      ["triceps-stretch-right", 30],
      ["standing-biceps-stretch-left", 30],
      ["standing-biceps-stretch-right", 30],
    ],
  },
  leg: {
    beginner: [
      ["side-hop", 30],
      ["squats", 12],
      ["squats", 12],
      ["side-lying-leg-lift-left", 12],
      ["side-lying-leg-lift-right", 12],
      ["side-lying-leg-lift-left", 12],
      ["side-lying-leg-lift-right", 12],
      ["backward-lunge", 14],
      ["backward-lunge", 14],
      ["donkey-kicks-left", 16],
      ["donkey-kicks-right", 16],
      ["donkey-kicks-left", 16],
      ["donkey-kicks-right", 16],
      ["left-quad-stretch-with-wall", 30],
      ["right-quad-stretch-with-wall", 30],
      ["knee-to-chest-stretch-left", 30],
      ["knee-to-chest-stretch-right", 30],
      ["wall-calf-raises", 12],
      ["wall-calf-raises", 12],
      ["sumo-squat-calf-raises-with-wall", 12],
      ["sumo-squat-calf-raises-with-wall", 12],
      ["calf-stretch-left", 30],
      ["calf-stretch-right", 30],
    ],
    intermediate: [
      ["jumping-jacks", 30],
      ["squats", 12],
      ["squats", 12],
      ["squats", 12],
      ["fire-hydrant-left", 12],
      ["fire-hydrant-right", 12],
      ["fire-hydrant-left", 12],
      ["fire-hydrant-right", 12],
      ["fire-hydrant-left", 12],
      ["fire-hydrant-right", 12],
      ["lunges", 14],
      ["lunges", 14],
      ["side-leg-circles-left", 12],
      ["side-leg-circles-right", 12],
      ["side-leg-circles-left", 12],
      ["side-leg-circles-right", 12],
      ["sumo-squat", 12],
      ["sumo-squat", 12],
      ["sumo-squat", 12],
      ["reverse-flutter-kicks", 12],
      ["reverse-flutter-kicks", 12],
      ["reverse-flutter-kicks", 12],
      ["wall-sit", 30],
      ["left-quad-stretch-with-wall", 30],
      ["right-quad-stretch-with-wall", 30],
      ["knee-to-chest-stretch-left", 30],
      ["knee-to-chest-stretch-right", 30],
      ["calf-raises-with-splayed-foot", 12],
      ["calf-raises-with-splayed-foot", 12],
      ["calf-raises-with-splayed-foot", 12],
      ["single-leg-calf-hop-left", 12],
      ["single-leg-calf-hop-right", 12],
      ["single-leg-calf-hop-left", 12],
      ["single-leg-calf-hop-right", 12],
      ["calf-stretch-left", 30],
      ["calf-stretch-right", 30],
    ],
    advanced: [
      ["burpees", 10],
      ["squats", 14],
      ["squats", 14],
      ["squats", 14],
      ["bottom-leg-lift-left", 12],
      ["bottom-leg-lift-right", 12],
      ["bottom-leg-lift-left", 12],
      ["bottom-leg-lift-right", 12],
      ["bottom-leg-lift-left", 12],
      ["bottom-leg-lift-right", 12],
      ["curtsy-lunges", 14],
      ["curtsy-lunges", 14],
      ["curtsy-lunges", 14],
      ["side-leg-circles-left", 12],
      ["side-leg-circles-right", 12],
      ["side-leg-circles-left", 12],
      ["side-leg-circles-right", 12],
      ["side-leg-circles-left", 12],
      ["side-leg-circles-right", 12],
      ["jumping-squats", 14],
      ["jumping-squats", 14],
      ["jumping-squats", 14],
      ["glute-kick-back-left", 12],
      ["glute-kick-back-right", 12],
      ["glute-kick-back-left", 12],
      ["glute-kick-back-right", 12],
      ["glute-kick-back-left", 12],
      ["glute-kick-back-right", 12],
      ["wall-sit", 40],
      ["left-quad-stretch-with-wall", 30],
      ["right-quad-stretch-with-wall", 30],
      ["lying-butterfly-stretch", 30],
      ["leaning-stretcher-raises", 16],
      ["leaning-stretcher-raises", 16],
      ["leaning-stretcher-raises", 16],
      ["wall-resisting-single-leg-calf-raise-left", 16],
      ["wall-resisting-single-leg-calf-raise-right", 16],
      ["wall-resisting-single-leg-calf-raise-left", 16],
      ["wall-resisting-single-leg-calf-raise-right", 16],
      ["wall-resisting-single-leg-calf-raise-left", 16],
      ["wall-resisting-single-leg-calf-raise-right", 16],
      ["calf-stretch-left", 30],
      ["calf-stretch-right", 30],
    ],
  },
  back: {
    beginner: [
      ["jumping-jacks", 30],
      ["arm-raises", 16],
      ["rhomboid-pulls", 14],
      ["side-arm-raise", 16],
      ["knee-push-ups", 14],
      ["side-lying-floor-stretch-left", 30],
      ["side-lying-floor-stretch-right", 30],
      ["arm-scissors", 30],
      ["rhomboid-pulls", 12],
      ["side-arm-raise", 14],
      ["knee-push-ups", 12],
      ["cat-cow-pose", 30],
      ["prone-triceps-push-ups", 14],
      ["reclined-rhomboid-squeezes", 12],
      ["reclined-rhomboid-squeezes", 12],
      ["prone-triceps-push-ups", 12],
      ["childs-pose", 30],
    ],
    intermediate: [
      ["jumping-jacks", 30],
      ["triceps-kickbacks", 14],
      ["incline-push-ups", 14],
      ["rhomboid-pulls", 12],
      ["floor-triceps-dips", 16],
      ["cat-cow-pose", 30],
      ["triceps-kickbacks", 12],
      ["incline-push-ups", 12],
      ["hip-hinge", 10],
      ["floor-triceps-dips", 14],
      ["side-lying-floor-stretch-left", 30],
      ["side-lying-floor-stretch-right", 30],
      ["hover-push-up", 14],
      ["swimmer-and-superman", 14],
      ["hover-push-up", 12],
      ["swimmer-and-superman", 12],
      ["childs-pose", 30],
    ],
    advanced: [
      ["jumping-jacks", 30],
      ["hyperextension", 14],
      ["pike-push-ups", 14],
      ["reverse-push-ups", 12],
      ["inchworms", 16],
      ["side-lying-floor-stretch-left", 30],
      ["side-lying-floor-stretch-right", 30],
      ["hyperextension", 12],
      ["pike-push-ups", 12],
      ["reverse-push-ups", 10],
      ["inchworms", 14],
      ["cat-cow-pose", 30],
      ["supine-push-up", 14],
      ["floor-y-raises", 14],
      ["supine-push-up", 12],
      ["reverse-slow-angels", 12],
      ["childs-pose", 30],
    ],
  },
}

const selectWorkouts = (part, difficulty) => {
  const imageUrl = "https://res.cloudinary.com/snapify/image/upload/flexin/"

  // validations
  if (!part || !difficulty) return []
  if (!workouts[part] || !workouts[part][difficulty]) {
    return []
  }

  const mapped = workouts[part][difficulty].map((item) => {
    const [name, longevity] = item
    const workout = allWorkouts.find((item) => item.image === name)
    return { ...workout, image: imageUrl + workout.image, longevity }
  })
  return mapped
}

export default selectWorkouts
